### ISSUE TITLE
incorrect case-sensitive comparison for addresses

### ISSUE THREAD

**Issue by smarx** [kumavis/eth-json-rpc-filters#4]
Address comparisons should be case-insensitive, but the comparison here is case-sensitive:

https://github.com/kumavis/eth-json-rpc-filters/blob/fa163bc215044221656bc8e5a29569ee5013d27f/log-filter.js#L68

This leads to problems when filtering logs using a mixed-case address. I believe that a `.toLowerCase()` is all that's required to fix this bug. In the meantime, the workaround is for developers to specify contract addresses in all lowercase.

This is potentially *one* thing leading to #2 and https://github.com/MetaMask/metamask-extension/issues/2393, but the main issue in the latter appears to be more about the timing, lifecycle, and interaction of various objects (providers, block trackers and filter middlewares).

**Comment by kumavis** [comment]
Thanks! fixed in `1.2.5`
